// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-04 21:05:49
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Tag is the golang structure for table tag.
type Tag struct {
	Id        int         `json:"id"         ` //
	Name      string      `json:"name"       ` //
	Desc      string      `json:"desc"       ` //
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
	DeletedAt *gtime.Time `json:"deleted_at" ` //
}
